### ISSUE TITLE
Deprecation header support

### ISSUE THREAD

**Issue by jorbascrumps** [jobilla/deprecated-routes-middleware#2]
I've been doing some research on deprecating endpoints with Laravel and came across this package - seems like a great solution!

Also in my research I discovered that usage of custom `X-` prefixed HTTP headers was apparently deprecated in 2012 ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#:~:text=Custom%20proprietary%20headers%20have%20historically,was%20defined%20in%20RFC%204229)). There is, however, a [draft](https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-deprecation-header) for a `Deprecation` header in the works. Is this something you would consider supporting in the future?

**Comment by hkan** [comment]
Hey Chris! Thanks for taking an interest in this package, and your kind words.

We have internally discussed your proposal and decided that we do not want to change the header name we are using. However, this doesn't mean that you should not be able to change it. We are going to introduce a new config option to set the header name to your liking.

It should be a fairly easy change and should be published in a few days, but don't take my word for it. 😄 We'll ping you as soon as it's ready.

**Comment by hkan** [comment]
Hey @jorbascrumps 👋

We have implemented the feature and it should be available in Composer soon. Let me know if there are any problems.

**Comment by jorbascrumps** [comment]
Hey @hkan! Thanks for the quick response and turnaround on the request! 😄
